<?php
return [
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_remote_actors` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `actor_uri` VARCHAR(500) NOT NULL,
        `actor_type` VARCHAR(40) NOT NULL,
        `preferred_username` VARCHAR(190) NOT NULL DEFAULT '',
        `display_name` VARCHAR(255) NOT NULL DEFAULT '',
        `inbox_url` VARCHAR(500) NOT NULL,
        `shared_inbox_url` VARCHAR(500) NULL,
        `public_key_id` VARCHAR(500) NOT NULL,
        `public_key_pem` TEXT NOT NULL,
        `key_owner_uri` VARCHAR(500) NOT NULL,
        `document_json` LONGTEXT NOT NULL,
        `fetched_at` DATETIME NOT NULL,
        `expires_at` DATETIME NOT NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `actor_uri` (`actor_uri`),
        KEY `expires_at` (`expires_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_inbox_receipts` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `activity_uri` VARCHAR(500) NOT NULL,
        `activity_type` VARCHAR(40) NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `key_id` VARCHAR(500) NOT NULL,
        `body_hash` CHAR(64) NOT NULL,
        `signature_date` DATETIME NOT NULL,
        `activity_json` LONGTEXT NOT NULL,
        `status` VARCHAR(30) NOT NULL,
        `result_code` VARCHAR(80) NOT NULL DEFAULT '',
        `received_at` DATETIME NOT NULL,
        `processed_at` DATETIME NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `activity_uri` (`activity_uri`),
        KEY `actor_received` (`actor_uri`, `received_at`),
        KEY `status_received` (`status`, `received_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_signature_replays` (
        `fingerprint` CHAR(64) NOT NULL,
        `key_id` VARCHAR(500) NOT NULL,
        `created_at` DATETIME NOT NULL,
        `expires_at` DATETIME NOT NULL,
        PRIMARY KEY (`fingerprint`),
        KEY `expires_at` (`expires_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_followers` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `follow_activity_uri` VARCHAR(500) NOT NULL,
        `follow_receipt_id` BIGINT UNSIGNED NOT NULL,
        `state` VARCHAR(30) NOT NULL DEFAULT 'pending',
        `response_activity_uri` VARCHAR(500) NULL,
        `followed_at` DATETIME NOT NULL,
        `moderated_at` DATETIME NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `actor_uri` (`actor_uri`),
        KEY `state_updated` (`state`, `updated_at`),
        KEY `remote_actor_id` (`remote_actor_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_following` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `follow_activity_uri` VARCHAR(500) NOT NULL,
        `state` VARCHAR(30) NOT NULL DEFAULT 'pending',
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `actor_uri` (`actor_uri`),
        UNIQUE KEY `follow_activity_uri` (`follow_activity_uri`),
        KEY `state_updated` (`state`, `updated_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "ALTER TABLE `{{prefix}}activitypub_deliveries` MODIFY COLUMN `event_id` BIGINT UNSIGNED NULL",
    "ALTER TABLE `{{prefix}}activitypub_deliveries` ADD COLUMN `delivery_type` VARCHAR(40) NOT NULL DEFAULT 'publication' AFTER `id`",
    "ALTER TABLE `{{prefix}}activitypub_deliveries` ADD COLUMN `activity_uri` VARCHAR(500) NULL AFTER `event_id`",
    "ALTER TABLE `{{prefix}}activitypub_deliveries` ADD COLUMN `payload_json` LONGTEXT NULL AFTER `activity_uri`",
    "ALTER TABLE `{{prefix}}activitypub_deliveries` ADD COLUMN `dedupe_key` CHAR(64) NULL AFTER `payload_json`",
    "ALTER TABLE `{{prefix}}activitypub_deliveries` ADD UNIQUE KEY `dedupe_key` (`dedupe_key`)",
    "ALTER TABLE `{{prefix}}activitypub_deliveries` ADD KEY `type_status_available` (`delivery_type`, `status`, `available_at`)",
];
