<?php
return [
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_blocks` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `block_type` VARCHAR(20) NOT NULL,
        `block_value` VARCHAR(500) NOT NULL,
        `reason` VARCHAR(255) NOT NULL DEFAULT '',
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `type_value` (`block_type`, `block_value`),
        KEY `updated_at` (`updated_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_remote_replies` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `remote_object_uri` VARCHAR(500) NOT NULL,
        `create_activity_uri` VARCHAR(500) NOT NULL,
        `last_activity_uri` VARCHAR(500) NOT NULL,
        `created_receipt_id` BIGINT UNSIGNED NOT NULL,
        `last_receipt_id` BIGINT UNSIGNED NOT NULL,
        `target_post_id` BIGINT UNSIGNED NOT NULL,
        `target_publication_generation` INT UNSIGNED NOT NULL,
        `target_object_uri` VARCHAR(500) NOT NULL,
        `parent_reply_id` BIGINT UNSIGNED NULL,
        `in_reply_to_uri` VARCHAR(500) NOT NULL,
        `content_html` MEDIUMTEXT NOT NULL,
        `content_text` TEXT NOT NULL,
        `content_hash` CHAR(64) NOT NULL,
        `moderation_state` VARCHAR(30) NOT NULL DEFAULT 'pending',
        `lifecycle_state` VARCHAR(20) NOT NULL DEFAULT 'active',
        `remote_published_at` DATETIME NULL,
        `remote_updated_at` DATETIME NULL,
        `deleted_at` DATETIME NULL,
        `moderated_at` DATETIME NULL,
        `moderator_user_id` BIGINT UNSIGNED NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `remote_object_uri` (`remote_object_uri`),
        UNIQUE KEY `create_activity_uri` (`create_activity_uri`),
        KEY `target_visible` (`target_post_id`, `target_publication_generation`, `moderation_state`, `lifecycle_state`, `created_at`),
        KEY `actor_updated` (`remote_actor_id`, `updated_at`),
        KEY `parent_reply_id` (`parent_reply_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_remote_interactions` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `semantic_key` CHAR(64) NOT NULL,
        `interaction_type` VARCHAR(20) NOT NULL,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `target_post_id` BIGINT UNSIGNED NOT NULL,
        `target_publication_generation` INT UNSIGNED NOT NULL,
        `target_object_uri` VARCHAR(500) NOT NULL,
        `current_activity_uri` VARCHAR(500) NOT NULL,
        `state` VARCHAR(30) NOT NULL,
        `activity_at` DATETIME NULL,
        `undone_at` DATETIME NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `semantic_key` (`semantic_key`),
        KEY `target_state` (`target_post_id`, `target_publication_generation`, `interaction_type`, `state`),
        KEY `actor_updated` (`remote_actor_id`, `updated_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_interaction_log` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `interaction_id` BIGINT UNSIGNED NOT NULL,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `activity_uri` VARCHAR(500) NOT NULL,
        `activity_type` VARCHAR(20) NOT NULL,
        `receipt_id` BIGINT UNSIGNED NOT NULL,
        `state` VARCHAR(20) NOT NULL,
        `undo_activity_uri` VARCHAR(500) NULL,
        `activity_at` DATETIME NULL,
        `undone_at` DATETIME NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `activity_uri` (`activity_uri`),
        UNIQUE KEY `undo_activity_uri` (`undo_activity_uri`),
        KEY `interaction_state` (`interaction_id`, `state`),
        KEY `actor_created` (`remote_actor_id`, `created_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
];
