<?php
return [
    "ALTER TABLE `{{prefix}}activitypub_following` ADD COLUMN `response_activity_uri` VARCHAR(500) NULL AFTER `follow_activity_uri`",
    "ALTER TABLE `{{prefix}}activitypub_following` ADD COLUMN `state_changed_at` DATETIME NULL AFTER `state`",
    "ALTER TABLE `{{prefix}}activitypub_following` ADD COLUMN `removed_at` DATETIME NULL AFTER `state_changed_at`",
    "ALTER TABLE `{{prefix}}activitypub_following` ADD COLUMN `last_error` TEXT NULL AFTER `removed_at`",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_follow_log` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `following_id` BIGINT UNSIGNED NOT NULL,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `activity_uri` VARCHAR(500) NOT NULL,
        `activity_type` VARCHAR(20) NOT NULL,
        `object_activity_uri` VARCHAR(500) NULL,
        `response_activity_uri` VARCHAR(500) NULL,
        `state` VARCHAR(30) NOT NULL,
        `payload_json` LONGTEXT NOT NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `activity_uri` (`activity_uri`),
        KEY `following_state` (`following_id`, `state`),
        KEY `actor_created` (`remote_actor_id`, `created_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_remote_objects` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `object_uri` VARCHAR(500) NOT NULL,
        `object_type` VARCHAR(40) NOT NULL DEFAULT 'Note',
        `source_activity_uri` VARCHAR(500) NULL,
        `last_activity_uri` VARCHAR(500) NULL,
        `content_html` MEDIUMTEXT NOT NULL,
        `content_text` TEXT NOT NULL,
        `content_hash` CHAR(64) NOT NULL,
        `human_url` VARCHAR(500) NULL,
        `metadata_json` LONGTEXT NOT NULL,
        `lifecycle_state` VARCHAR(20) NOT NULL DEFAULT 'active',
        `remote_published_at` DATETIME NULL,
        `remote_updated_at` DATETIME NULL,
        `fetched_at` DATETIME NOT NULL,
        `expires_at` DATETIME NOT NULL,
        `deleted_at` DATETIME NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `object_uri` (`object_uri`),
        KEY `actor_lifecycle` (`remote_actor_id`, `lifecycle_state`, `remote_published_at`),
        KEY `expires_at` (`expires_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_owner_interactions` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `semantic_key` CHAR(64) NOT NULL,
        `interaction_type` VARCHAR(20) NOT NULL,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `target_object_uri` VARCHAR(500) NOT NULL,
        `current_activity_uri` VARCHAR(500) NOT NULL,
        `state` VARCHAR(30) NOT NULL,
        `activated_at` DATETIME NULL,
        `undone_at` DATETIME NULL,
        `last_error` TEXT NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `semantic_key` (`semantic_key`),
        KEY `actor_state` (`remote_actor_id`, `state`),
        KEY `target_state` (`target_object_uri`, `interaction_type`, `state`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_owner_action_log` (
        `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
        `owner_interaction_id` BIGINT UNSIGNED NULL,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `target_object_uri` VARCHAR(500) NOT NULL,
        `activity_uri` VARCHAR(500) NOT NULL,
        `activity_type` VARCHAR(30) NOT NULL,
        `object_activity_uri` VARCHAR(500) NULL,
        `payload_json` LONGTEXT NOT NULL,
        `state` VARCHAR(30) NOT NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `activity_uri` (`activity_uri`),
        KEY `interaction_state` (`owner_interaction_id`, `state`),
        KEY `actor_created` (`remote_actor_id`, `created_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS `{{prefix}}activitypub_reply_targets` (
        `post_id` BIGINT UNSIGNED NOT NULL,
        `remote_object_id` BIGINT UNSIGNED NOT NULL,
        `remote_actor_id` BIGINT UNSIGNED NOT NULL,
        `actor_uri` VARCHAR(500) NOT NULL,
        `in_reply_to_uri` VARCHAR(500) NOT NULL,
        `created_at` DATETIME NOT NULL,
        `updated_at` DATETIME NOT NULL,
        PRIMARY KEY (`post_id`),
        KEY `remote_object_id` (`remote_object_id`),
        KEY `remote_actor_id` (`remote_actor_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
];
